### ISSUE TITLE
[Feature Request] 可以加在搜索结果中筛选吗

### ISSUE THREAD

**Issue by LuminousXLB** [dujiajun/jcourse#1]
![image](https://user-images.githubusercontent.com/23524048/133917308-51836fe4-e54c-4711-8a68-08d7129069f7.png)

**Comment by dujiajun** [comment]
暂时不考虑。因为搜索功能的用意是快速定位到某门课程，那么在基础课教师较多的情况下应该搜索教师名称而不是课程名。如果想对比某门课各个老师的情况，可以直接在课程详情界面查看“其他老师的XXX课”。
