### ISSUE TITLE
移动设备上，网页顶部导航栏显示溢出

### ISSUE THREAD

**Issue by ADSWT518** [dujiajun/jcourse#2]
![1](https://user-images.githubusercontent.com/58338486/154876964-342cda55-29b1-4cce-bb7d-00efb59d8885.jpg)

测试设备：华为P30
测试浏览器：Microsoft Edge、Firefox、华为浏览器

在电脑端Edge的开发者工具中，模拟IPhone SE等小屏设备时，也会出现相同问题。

**Comment by ADSWT518** [comment]
> 微调了小屏幕上的按钮外边距，现在可以试一下是否还存在问题

在我的手机上似乎还是不行 :joy: 然后电脑端Edge模拟Samsung Galaxy S8+的时候也会有问题。

或许可以把顶部导航栏改成「如果溢出了就可以左右滑动」的形式？这样可行吗 :thinking:

**Comment by dujiajun** [comment]
用的antd似乎没找到合适的配置。不过这个问题之前应该是注意到的，不过减小菜单的间距的样式在重构之后失效了，现在加了!important应该调好了。

**Comment by ADSWT518** [comment]
现在显示正常了！感谢开发者！
